### PR TITLE
SugarCli Module Code Generator

### PR DESCRIPTION
**Pull request by jcora-nyt**

### CODE REVIEW

**Comment by jcora-nyt** [comment]
@ashutoshsinghnyt: I added Sidecar files to this PR that I forgot in the first pass

**Comment by ashutoshsinghnyt** [comment]
The repair works very well :+1:  . 
Reviewed the module creation process and below are some of the observations :
- Should have the ability to define Module Name. Creates module name with the Key. if this can be addressed it will reduce the rework to rename the module name.
- Option to exclude team security feature is missing. We may or may not want to add extra team fields for some of the modules.
- Repair process takes two executions to generate the SQL for Table Schema for the new module .
- Creates only basic type module, However, it will be the same for most of the new modules.

**Comment by jcora-nyt** [comment]
- Removed team security from the default module type. We can add an option later to specify different module configurations and types when needed.
- Increased possible key (prefix) size for module to 5 from 3.
- Remove prefix, if specified, from module name in language file

**Comment by ashutoshsinghnyt** [comment]
Verified, discussed with @jcora-nyt regarding the sub menu in the top menu, that can be addressed later. Works fine for the basic module structure. Can be merged now.

**Comment by jcora-nyt** [comment]
Merging

**Pull request merged**
