### PR TITLE
Support Non-DB Fields for Code Generation

### PR DESCRIPTION
**Pull request by jcora-nyt**
@utsab-nyt: Wait until you complete and live test the new features until you begin reviewing.

### CODE REVIEW

**Comment by jcora-nyt** [comment]
@utsab-nyt: this PR is updated with new approach to relationships. Verified relationships generated from skeleton code works in SugarQuery and SugarAPI.

**Comment by utsab-dev** [comment]
@jcora-nyt When I am trying to create a nondb field it is throwing an exception and not creating the field.
Command:
`app_cli code:nondbField -m Contacts_NYT -r Contacts -p . --name testfield`
Response:
`[InvalidArgumentException]
 An instance of RecursiveIterator or IteratorAggregate creating it is required`

**Comment by jcora-nyt** [comment]
@utsab-nyt: I just performed the `nondbField` operation and it worked fine. If you didn't adjust the Sugar NYT _composer.json_ file to install the branch, you may have missed running composer for the CLI tool as well.

cli
vardefs

**Comment by utsab-dev** [comment]
I did update the Composer as per the code shared by you in Slack, will try again.

**Comment by utsab-dev** [comment]
@jcora-nyt Suggestions:
1. Should be able to create a nondb field of a related module of a default field.
eg app_cli code:nondbField -m Contacts_NYT_Preferred -r Contacts -p . --name assistant
2.  Should be able to create a nondb field which is not related to any specific module.

**Comment by jcora-nyt** [comment]
Creating non-DB fields that follow the related module convention has
limited utility and is not a straightforward implementation, in my opinion.

As part of this PR, I added a new field type, `field:nondb` that does
exactly what item 2 suggested.

**Pull request merged**
